version: '3.3'

services:
    localstack:
        container_name: 'k6-jslib-aws-localstack'
        image: 'localstack/localstack:4.12.0@sha256:0df3a97da57de03a588c05d9b8f390f15c7033fc7c4512f94619d344bc3cd317'
        ports:
            - '127.0.0.1:4566:4566' # LocalStack Gateway
            - '127.0.0.1:4510-4559:4510-4559' # external services port range
        environment:
            - SERVICES=s3,secretsmanager,sqs,kms,ssm,kinesis,lambda
            - S3_SKIP_SIGNATURE_VALIDATION=0 # enable signature validation
            - DEBUG=${DEBUG-}
            - PERSISTENCE=${PERSISTENCE-}
        volumes:
            - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
            - './localstack/init:/etc/localstack/init'
            - '/var/run/docker.sock:/var/run/docker.sock'
